python src/train.py --experimentID $1 \
    --gpu_id $2 \
    --task both \
    --dataset automotive \
    --shuffle \
    --batch_size 20 \
    --learning_rate 0.001 \
    --num_epoch 20 \
    --eval_epoch_num 1 --eval_after_epoch_num 5 \
    --log_iter_num 1 \
    --num_aspects 291 --num_user 2928 --num_item 1835 \
    --feat_dim 200 \
    --max_review_num 30 \
    --save_model --save_after_epoch_num 5 --save_epoch_num 2 \
    --dropout 0.2 --cnn_out_channel 200 --im_kernel_size 3